trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    displayName: 'Use Node 18.x'
    inputs:
      versionSpec: 18.x
  - task: Npm@1
    displayName: NPM Install
    inputs:
      command: 'install'
      workingDir: '$(System.DefaultWorkingDirectory)'
      verbose: true
  - task: Npm@1
    displayName: 'ng build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'
      workingDir: $(System.DefaultWorkingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    condition: |-
      and(
        succeeded(),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    inputs:
      ArtifactName: Angular
      PathtoPublish: $(System.DefaultWorkingDirectory)/dist
      publishLocation: Container