trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    displayName: 'Use Node 18.x'
    inputs:
      versionSpec: 18.x
  - task: Npm@1
    displayName: NPM Install
    inputs:
      command: custom
      verbose: true
      workingDir: $(System.DefaultWorkingDirectory)
      customCommand: 'install  --legacy-peer-deps --force'
      
  - task: Npm@1
    displayName: Install Moment
    inputs:
      command: custom
      verbose: true
      workingDir: $(System.DefaultWorkingDirectory)
      customCommand: 'install @angular/material-moment-adapter --force'

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: 'custom'
      verbose: true
      workingDir: $(System.DefaultWorkingDirectory)
      customCommand: 'run build'
    
  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    condition: |-
      and(
        succeeded(),
        ne(variables['Build.Reason'], 'PullRequest')
      )
    inputs:
      ArtifactName: Angular
      PathtoPublish: $(System.DefaultWorkingDirectory)/dist/delivery-driver-angular-app
      publishLocation: Container